services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: votedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  database: